### ISSUE TITLE
Great Job !

### ISSUE THREAD

**Issue by ghost** [aramvisser/bulma-steps#1]
Hi @aramvisser ,

Just to tell you made an amazing job with this extension.
Yours is very complete.
What do you think if we work together to improve the bulma-timeline extension too based on your steps version ? Let me know if you're interesting.

Regards

**Comment by aramvisser** [comment]
Hi @Wikiki,

Thanks for your compliments!

A simple timeline is already possible using this steps component, but it's not meant for it. To be a proper timeline component would require a new implementation, separate from the steps component. But similar ideas and techniques can be reused of course.

I'm willing to work together on improving your version. How would you want to do that?

The first think I would like to do is to create a proper documentation page with examples, like I did with this steps component. Would that be possible?

**Comment by ghost** [comment]
Hi,

You're right, working on a documentation page like you did is a priority.
I'll be glad to have your help on it.
I just invited you on my project.

**Comment by ghost** [comment]
Hi,

can you please help me to create a documentation page for my extensions ?
Maybe you could share with your github.io page source ?

Regards

**Comment by aramvisser** [comment]
Hi @Wikiki,

The source for the github page is this repository. It doubles as a Jekyll website.

I looked into creating a documentation page for your steps extensions. But since you have so many extensions, I think it would make more sense to create a single documentation site for all your extensions.

**Comment by ghost** [comment]
Hi,

That's what I do.
It's just my first time with jekyll so....I need some time to handle it.

Envoyé de ProtonMail mobile

-------- Message d'origine --------
