### ISSUE TITLE
option for horizontal progess bar on mobile device

### ISSUE THREAD

**Issue by nikugogoi** [aramvisser/bulma-steps#10]
It would be helpful if a class like is-mobile can be used to force horizontal display of the bar in mobile devices and similarly in other viewports

**Comment by aramvisser** [comment]
There is an `is-horizontal` class available to always force the progress bar to be horizontal. You can look at the [alignment section](https://aramvisser.github.io/bulma-steps/#alignment) in the documentation to see how it works.

**Comment by nikugogoi** [comment]
sorry that was really simple... should have tried some more
