### ISSUE TITLE
Auto scroll for overflow

### ISSUE THREAD

**Issue by ghost** [aramvisser/bulma-steps#2]
Hi again,

I had an idea for the steps (not yet implemented in my version but on my todo list), maybe it could interest you: be able to set an autoscroll (for example instead of getting vertical on mobile then keep the horizontal layout but with an x scroll.)
It could be used to fit in a zone (or with max-width / max-height) without changing layout and getting too long.

Regards

**Comment by aramvisser** [comment]
Autoscrolling is usefull, but It should not be implemented per component. Wide tables would also be a candidate for an autoscrolling function, for example.

I actually use a separate css class just for that in my projects.

css:
```css
.scrollable {
  max-width: 100%;
  overflow-x: auto;
}
```
html:
```html
<div class="scrollable">
  <ul class="steps is-horizontal">...</ul>
</div>
```

This works for all content contained inside it.

**Comment by ghost** [comment]
Perfect. Thanks
