### ISSUE TITLE
please consider publish to npm.

### ISSUE THREAD

**Issue by kresli** [aramvisser/bulma-steps#7]
Currently there is no other way to use this awesome extension without cloning or downloading it which makes harder to use it as dependency in other projects. If you publish this on npm this would be great, however if you dont want to bother to publish it simply created package.json would help too.
Thanks

**Comment by aramvisser** [comment]
Hi @kresli,

I published the package to NPM: https://www.npmjs.com/package/bulma-steps-component

Thanks for your help!
